[package]
name = "bipack_ru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
lazy_static = "1.4.0"

[dev-dependencies]
base64 = "0.21.4"
hex = "0.4.3"
